### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by shingoishimura** [shingoishimura/furima-33484#9]
https://furima-33484.herokuapp.com/

shingo  1783

出品者用のメールアドレスとパスワード shingoishimura@gmail.com  mitumasa0710

購入者用のメールアドレスとパスワード inaba1029@yahoo.co.jp mitumasa0710

購入用カードの番号・期限・セキュリティコード 4242424242424242   2/23 123

**Comment by mo1015** [comment]
ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます:tada:
おめでとうございます！
**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
